services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bde-events-api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: BDE_events
      DB_USERNAME: bde_user
      DB_PASSWORD: bde_password

  mysql:
    image: mysql:8.0
    container_name: bde-events-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: BDE_events
      MYSQL_USER: bde_user
      MYSQL_PASSWORD: bde_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - bde_events_mysql_data:/var/lib/mysql

volumes:
  bde_events_mysql_data: