services:
  api:
    image: bde-events-api
    build:
      context: ./bde-events-api
      dockerfile: Dockerfile
    container_name: bde-events-api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: BDE_events
      DB_USERNAME: bde_user
      DB_PASSWORD: bde_password

  mysql:
    image: mysql:8.0
    container_name: bde-events-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: BDE_events
      MYSQL_USER: bde_user
      MYSQL_PASSWORD: bde_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - bde_events_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bde-events-phpmyadmin
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

  frontend:
    image: bde-events-react
    build:
      context: ./bde-events-react
      dockerfile: Dockerfile
    container_name: bde-events-react
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  bde_events_mysql_data:
